# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-12 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('family', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water', models.CharField(default='0 0 0 0 0 0 0 0 0 0 0 0', max_length=25)),
                ('watchman', models.CharField(default='0 0 0 0 0 0 0 0 0 0 0 0', max_length=25)),
                ('maid', models.CharField(default='0 0 0 0 0 0 0 0 0 0 0 0', max_length=25)),
                ('electricity', models.CharField(default='0 0 0 0 0 0 0 0 0 0 0 0', max_length=25)),
                ('gascylinder', models.CharField(default='0 0 0 0 0 0 0 0 0 0 0 0', max_length=25)),
                ('tv', models.CharField(default='0 0 0 0 0 0 0 0 0 0 0 0', max_length=25)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Family')),
            ],
        ),
    ]
