# Generated by Django 3.1.6 on 2021-02-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0003_bills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='electricity',
            field=models.CharField(default='1 0 0 0 0 0 0 0 0 0 0 0', max_length=25),
        ),
    ]
